Lint/EndAlignment:
  AlignWith: variable

Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Metrics/LineLength:
  Max: 113

Metrics/ClassLength:
  Max: 113

Metrics/ModuleLength:
  Max: 113

Metrics/ModuleLength:
  CountComments: false
  Exclude:
    - test/**/*.rb

Metrics/ClassLength:
  CountComments: false
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  CountComments: false
  Exclude:
    - test/**/*.rb

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Exclude:
    - 'config/environments/*.rb'

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'db/schema.rb'

Style/ExtraSpacing:
  Exclude:
    - 'config/environments/*.rb'

Style/PredicateName:
  Exclude:
    - 'app/helpers/application_helper.rb'

Style/SafeNavigation:
  Enabled: false
